
server:
    port: 8080
    servlet:
        context-path: /

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?serverTimeZone=Asia/Soul
        username: root
        password: Hh0807!!

mybatis:
    mapper-locations: 'classpath:com/baldcharm/blog/mapper/*.xml'