
server:
    port: 8080
    servlet:
        context-path: /

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?serverTimeZone=Asia/Soul
        username: root
        password: Hh0807!!
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
            show-sql: true
            properties:
                hibernate.format_sql: true

mybatis:
    mapper-locations: 'classpath:com/baldcharm/blog/mapper/*.xml'